# Generated by Django 3.1.4 on 2023-02-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230201_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='deadline',
        ),
    ]
